# Generated by kpex 0.3.2
crashbackups stop
drc off
gds read /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/layout/PFD_std.gds
load PFD_std
select top cell
flatten PFD_std_flat
load PFD_std_flat
cellname delete PFD_std -noprompt
cellname rename PFD_std_flat PFD_std
select top cell
extract path /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/pex/PFD_std__PFD_std/magic_RC
extract do resistance
extract all
ext2sim labels on
ext2sim
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice rthresh 100
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/pex/PFD_std__PFD_std/magic_RC -o /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/pex/PFD_std__PFD_std/magic_RC/PFD_std.pex.spice
quit -noprompt
