# Generated by kpex 0.3.2
crashbackups stop
drc off
gds read /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/layout/LC_VCO_L.gds
load LC_VCO
select top cell
flatten LC_VCO_flat
load LC_VCO_flat
cellname delete LC_VCO -noprompt
cellname rename LC_VCO_flat LC_VCO
select top cell
extract path /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/pex/LC_VCO_L__LC_VCO/magic_RC
extract do resistance
extract all
ext2sim labels on
ext2sim
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice rthresh 100
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/pex/LC_VCO_L__LC_VCO/magic_RC -o /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/pex/LC_VCO_L__LC_VCO/magic_RC/LC_VCO.pex.spice
quit -noprompt
