# Generated by kpex 0.3.2
crashbackups stop
drc off
gds read /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/layout/dsm_and_freq_divider.gds
load dsm_and_freq_divider
select top cell
flatten dsm_and_freq_divider_flat
load dsm_and_freq_divider_flat
cellname delete dsm_and_freq_divider -noprompt
cellname rename dsm_and_freq_divider_flat dsm_and_freq_divider
select top cell
extract path /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/pex/dsm_and_freq_divider__dsm_and_freq_divider/magic_RC
extract do resistance
extract all
ext2sim labels on
ext2sim
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice rthresh 100
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/pex/dsm_and_freq_divider__dsm_and_freq_divider/magic_RC -o /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/pex/dsm_and_freq_divider__dsm_and_freq_divider/magic_RC/dsm_and_freq_divider.pex.spice
quit -noprompt
