# Generated by kpex 0.3.2
crashbackups stop
drc off
gds read /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/layout/CP.gds
load CP_lvs
select top cell
flatten CP_lvs_flat
load CP_lvs_flat
cellname delete CP_lvs -noprompt
cellname rename CP_lvs_flat CP_lvs
select top cell
extract path /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/pex/CP__CP_lvs/magic_RC
extract do resistance
extract all
ext2sim labels on
ext2sim
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice rthresh 100
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/pex/CP__CP_lvs/magic_RC -o /foss/designs/iic_osic_tools/frac-n-pll-vco-unic_cass/pex/CP__CP_lvs/magic_RC/CP_lvs.pex.spice
quit -noprompt
